### ISSUE TITLE
fstrim output coming up blank

### ISSUE THREAD

**Issue by jahanson** [onedr0p/kubanetics#4]
I'm not sure why I seem to be the only one experiencing this issue but here are my notes:

On further investigation I pulled some of this info and was able to manually run the command in your container after nsenter.

The `mountinfo` file created at `/tmp/mountinfo` contains this nonsense. Is this the expected kind of input `fstrim` wants?
![image](https://github.com/onedr0p/kubanetics/assets/1548511/12040961-0ddf-4f87-99c1-1d8f81adaa52)

Using `fstrim -v a` worked but I don't believe it covered all of the mounts. But this isn't an issue with your script.
![image](https://github.com/onedr0p/kubanetics/assets/1548511/1dc1244e-5625-42c1-b498-52edce29ef23)

**Comment by onedr0p** [comment]
Yes, fstrim can read `/tmp/mountinfo` just the way it is

https://man7.org/linux/man-pages/man8/fstrim.8.html

<img width="691" alt="image" src="https://github.com/onedr0p/kubanetics/assets/213795/45a193ec-d8f5-4c14-a6a9-c7e87b7b4f49">

**Comment by jahanson** [comment]
How does yours look? My `fstrim` output is still coming up empty with that input.

**Comment by onedr0p** [comment]
I get this output in the job:

```
❯ k logs -n kube-system fstrim-28480320-77g4v
/var/lib/containerd: 901.1 GiB (967532859392 bytes) trimmed on /dev/sda6
```

**Comment by jahanson** [comment]
Sorry, I meant your `/tmp/mountinfo` .

**Comment by onedr0p** [comment]
I need to get the pod running to check but last I remember it looked like your output...
