### ISSUE TITLE
fstrim fails to run nsenter

### ISSUE THREAD

**Issue by joryirving** [onedr0p/kubanetics#48]
I haven't had this successfully run since 2024.9.1.

Both `.2` and `.3` return the following error:

```
nsenter: failed to execute bash: No such file or directory 
```

My hr: https://github.com/joryirving/home-ops/blob/40d22ca802b8140a4b538181d7892e87384c3de2/kubernetes/main/apps/kube-tools/fstrim/app/helmrelease.yaml

**Comment by onedr0p** [comment]
Interesting, nothing has changed in the script for awhile and nothing has really changed with the repo...

https://github.com/onedr0p/kubanetics/compare/2024.9.1...2024.9.3

Maybe Talos 1.8.0 broke it?

**Comment by joryirving** [comment]
I also looked at the releases and saw nothing had changed. You may be correct that this is a talos issue.

**Comment by onedr0p** [comment]
I think I spotted the cause, Talos uses a slim kubelet image by default now which doesn't include bash

https://github.com/siderolabs/kubelet/commit/6c43bd116674237704f006c8377bac967a8a54f4

**Comment by joryirving** [comment]
That fixed it! Thanks!
